/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class br_com_luisdemarchi_FaceDetectionJni */

#ifndef _Included_br_com_luisdemarchi_FaceDetectionJni
#define _Included_br_com_luisdemarchi_FaceDetectionJni
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_br_com_luisdemarchi_FaceDetectionJni_find_1objects(JNIEnv *jenv, jclass jcls, jfloatArray jarg1, jint jarg2, jbyteArray jarg3, jfloat jarg4, jbyteArray jarg5, jint jarg6, jint jarg7, jint jarg8, jfloat jarg9, jfloat jarg10, jfloat jarg11, jfloat jarg12);

JNIEXPORT jint JNICALL Java_br_com_luisdemarchi_FaceDetectionJni_cluster_1detections(JNIEnv *jenv, jclass jcls, jfloatArray jarg1, jint jarg2);

JNIEXPORT jint JNICALL Java_br_com_luisdemarchi_FaceDetectionJni_update_1memory(JNIEnv *jenv, jclass jcls, jobject jarg1, jfloatArray jarg2, jintArray jarg3, jint jarg4, jint jarg5, jfloatArray jarg6, jint jarg7, jint jarg8);

#ifdef __cplusplus
}
#endif
#endif
